package element;

public enum Category {
    ALKALI_METALS,
    ALKALINE_EARTH_METALS,
    LANTHANOIDS,
    ACTINOIDS,
    TRANSITION_METALS,
    POST_TRANSITION_METALS,
    METALLOIDS,
    REACTIVE_NONMETALS,
    NOBLE_GASES,
    UNKNOWN;
}
